//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallPostByTechBrij.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> FriendId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
